### ISSUE TITLE
兼容64位的问题我已经解决了..比较多写不出来..需要知道的可以私我

### ISSUE THREAD

**Issue by 958184238** [szitguy/RecordVideoDemo#25]

**Comment by youxin11544** [comment]
给你发了邮件，没回

**Comment by LwkCoder** [comment]
请问怎么解决？如何私你？

**Comment by GaoHanqiong** [comment]
你好，能留个联系方式吗？ @958184238

**Comment by jacky1234** [comment]
你好，怎么解决呢？谢谢！847564732@qq.com

**Comment by syab11** [comment]
刚询问了	958184238 
她的办法是在build中的defaultConfig添加        
ndk{
            abiFilters "armeabi-v7a"
        }
其他的.so文件夹删除  我测试时没有报64bit的错了。
但项目中含有多个第三方.so，这样较大的改动怕引起其他的问题

**Comment by LwkCoder** [comment]
我也猜到了楼上说的这种做法：强制要求所有so加载32位的，编译的时候不会把64位so库打包进去。但是实际使用过程中log会输出warning，而且一般来说，项目中其他so库大多数都有兼容64位手机，单独为了这个功能砍掉哪些已经兼容的so库明显不可取。
