### ISSUE TITLE
视频录制时清晰度和流畅度设置

### ISSUE THREAD

**Issue by l455202325** [szitguy/RecordVideoDemo#31]
如题，如何调整录制出来的视频的 清晰度及流畅度

**Comment by l455202325** [comment]
自己找的坑还是要自己来填平啊 ，问题已经解决啦

**Comment by simank** [comment]
如何解决的呀

**Comment by langyazhouwl** [comment]
如何调整清晰度

**Comment by l455202325** [comment]
WXLikeVideoRecorder里面设置
 recorder.setVideoBitrate(2*1024*1024);
就可以调整清晰度了 但是流畅度还没有找到怎么设置
